language: node_js
node_js: stable
cache:
  directories:
    - "node_modules"
before_install:
- openssl aes-256-cbc -K $encrypted_4514352cb17e_key -iv $encrypted_4514352cb17e_iv
  -in .travis/khs1994-robot.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "khs1994-merge-robot"
- git config --global user.email "ai@khs1994.com"
- echo "TZ='Asia/Shanghai'; export TZ" >> ~/.profile
- . ~/.profile
install:
- git ls-files | while read file; do touch -d $(git log -1 --format="@%ct" "$file") "$file"; done
- npm install gitbook -g
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
after_success:
 - sh .travis/deploy.sh
branches:
  only:
  - master
env:
  global:
  - REPO: git@github.com:khs1994-gitbook/docker_practice.git
addons:
  ssh_known_hosts:
  - github.com
