version: "3"
services:

  docker_practice:
    build: ./.travis
    image: ccr.ccs.tencentyun.com/docker_practice/docker_practice:latest
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/gitbook-src
    command: server
