version: "3"
services:

  docker_practice:
    build: ./.travis
    image: yeasy/docker_practice:latest
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/gitbook-src
    command: server

  windows:
    image: nginx:alpine
    volumes:
      - ./:/srv/www
      - .travis/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4000:4000
