on:
  push:
  pull_request:

name: CI

jobs:
  build:
    name: Build GitBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Build
        uses: docker://yeasy/docker_practice
        with:
          args: build
