on:
  push:
  pull_request:

name: CI

jobs:
  build:
    name: Build GitBook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Build
        uses: docker://yeasy/docker_practice
        with:
          args: build
      - name: vuepress
        run: |
          npx vuepress build
      - name: Upload Vuepress dist
        uses: docker://pcit/pages
        env:
          PCIT_EMAIL: khs1994@khs1994.com
          PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
          PCIT_GIT_URL: github.com/docker-practice/vuepress
          PCIT_KEEP_HISTORY: "1"
          PCIT_LOCAL_DIR: .vuepress/dist
          PCIT_MESSAGE: Sync from yeasy/docker-practice@${{github.sha}} by PCIT
          PCIT_TARGET_BRANCH: master
          PCIT_USERNAME: khs1994
